server:
  port: 8090

spring:
  application:
    name: springcloud-security

  devtools:
    restart:
      #exclude: templates/**,static/** #不重启
      #additional-paths: src/main/java  #重启
      enabled: false #都不重启

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jnhouse?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  thymeleaf:
    prefix: classpath:/templates/ # 不加这个，接口自动到resources/templates目录下找与接口返回的相同名称的html
    cache: false

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/






