server:
  port: 8089

spring:
  application:
    name: zuul_Service

  devtools:
    restart:
      #exclude: templates/**,static/** #不重启
      #additional-paths: src/main/java  #重启
      enabled: false #都不重启

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: providerService #http://localhost:8089/api-a/hello_ribbon?name=a
    bd:
      path: /bd/**
      url : https://www.baidu.com
  host:
    connect-timeout-millis: 15000 #连接超时时间
    socket-timeout-millis: 60000 #socket发送超时时间


#  prefix: /api-gateway Zuul配置访问前缀：访问时候需要加上前缀，eg：http://localhost:8089/api-gateway/api-a/hello_ribbon?name=a

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/