cas:
  server-url-prefix: http://192.168.236.131:8080/cas
  server-login-url: http://192.168.236.131:8080/cas/login
  client-host-url: http://localhost:9100
  validation-type: cas

server:
  port: 9100
