server:
  port: 8085

spring:
  application:
    name: servicefour
  redis:
    host: 192.168.236.132
    port: 6379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: -1ms
    database: 0

  thymeleaf:
    prefix: classpath:/templates/ # 不加这个，接口自动到resources/templates目录下找与接口返回的相同名称的html，如访问localhost:8085/hello 自动跳转到hello.html
    cache: false

  devtools:
    restart:
      #exclude: templates/**,static/** #不重启
      #additional-paths: src/main/java  #重启
      enabled: false #都不重启

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jnhouse?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/xmxe/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"


