server:
  port: 8084
spring:
  application:
    name: servicethree
  cloud:
    gateway:
      routes:
      - id: baidu
        uri: http://www.baidu.com/
        predicates:
        - Path=/baidu/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/